language: java

addons:
  postgresql: "9.4"

python:
  - "2.7"

before_install:
  - sudo rm /etc/mavenrc
  - export MAVEN_OPTS=-Dmaven.repo.local=/home/travis/.m2/repository -Xmx1024M -XX:MaxPermSize=192m --quiet
  - whoami
  - java -version
  - python --version
  - pwd
  - mvn help:system
  - sudo apt-get install -qq cloc
  - echo "Initialising default settings"
  - cd utilities/project_helpers
  - sed -i'' 's/tomcat.(TOMCAT_VERSION)/travis/' ./config/variable.makefile.example
  - sed -i'' 's/lr.common.theme = /lr.common.theme = \/tmp\/dspace/' ./config/local.conf.dist
  - sed -i'' 's/lr.dspace.dir = /lr.dspace.dir = \/tmp\/dspace/' ./config/local.conf.dist
  - "cd config && cp local.conf.dist ../sources/local.properties && cd .."
  - "cd scripts"
  - echo "Creating dspace DB user and databases"
  - sudo -u postgres createuser --superuser dspace
  - make create_databases
  - echo "Installing prerequisites"
  - ./setup.prerequisites.sh

# Skip install stage, as we'll do it below
install: "echo 'Skipping install stage, dependencies will be downloaded during build and test stages.'"

# Two stage Build and Test
# 1. Install & Unit Test APIs
# 2. Assemble DSpace
script:
  - make new_deploy
  - cloc ../
  - make print_message
  - make test_dspace_database
  - make test_utilities_database
  - cd ../sources/ && mvn -Dmaven.test.skip=false -Dtest=cz.cuni.mff.ufal.dspace.**.*Test,cz.cuni.mff.ufal.*Test -DfailIfNoTests=false test && cd ../
  - #make selenium_tests || echo "Tests failed"
